### ISSUE TITLE
Trying to request new access tokens via the API fails

### ISSUE THREAD

**Issue by benmag** [ohmybrew/laravel-shopify#104]
I'm trying to request new access tokens via the API (https://help.shopify.com/en/api/getting-started/authentication/oauth/api-credential-rotation#step-5-request-new-access-tokens) but it just keeps getting rejected

```
Oauth error invalid_request: Could not find Shopify API application with api_key
```

Code snippet 
```
    session(['shopify_domain' => 'test123.myshopify.com']);

    $shop = \ShopifyApp::shop();
    try {
        $foo = $shop->api()->request(
            'POST',
            "/admin/oauth/access_token",
            [
                'json' => [
                    'client_id' => 'xxxx',
                    'client_secret' => 'xxxx',
                    'refresh_token' => 'xxxx-xxxx',
                    'access_token' => 'xxxx',
                ],
            ]
        );
    } catch(Exception $e) {
        dd($e->getResponse()->getBody()->getContents());
    }
```

Does anyone have any ideas for what might be going on?

**Comment by ohmybrew** [comment]
Client ID would be the API key, is the key correct for sure?

**Comment by benmag** [comment]
Yep, it's using the correct key 

Have you been able to check if it works for you?

**Comment by ohmybrew** [comment]
Not yet, have not had the chance yet. Will do. My gut thinks it's not an
issue with this side of things though. As the regular token request works
without issue.

On Sep. 17, 2018 23:03, "Ben Magg" <notifications@github.com> wrote:

Yep, it's using the correct key

Have you been able to check if it works for you?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ohmybrew/laravel-shopify/issues/104#issuecomment-422224086>,
or mute the thread

**Comment by benmag** [comment]
I think you might be right. 

Closing this for now since I don't think it's a laravel-shopify specific issue anymore

**Comment by ohmybrew** [comment]
I'll try tonight to be sure with a request and watch the headers and
response but I think this is something quirk on Shopify side.

On Sep. 18, 2018 01:41, "Ben Magg" <notifications@github.com> wrote:

I think you might be right.

Closing this for now since I don't think it's a laravel-shopify specific
issue anymore

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ohmybrew/laravel-shopify/issues/104#issuecomment-422249146>,
or mute the thread
