### ISSUE TITLE
Redirect To App Hosted url While accepting or decline the billing charges.

### ISSUE THREAD

**Issue by dhruv728462** [ohmybrew/laravel-shopify#134]
Hey Everyone, I have Developed a shopify app and i have used this Laravel Shopify Plugin.I have submitted My App for shopify store and that app is working good but only one problem that i'm facing for a long time that whenever i'm decline or accepting the billing charge on my app it will redirect to my hosting url and then again redirect to shopify app. I have tried everything in Traits/BillingControllerTrait.php  in vendor folder but it is redirecting to my hosting URL and then again back to shopify Dashboard that should not do any app. Any app should not redirect to any other URL after coming to Shopify Dashboard.So Can anyone tell me what can be solution for that it will be great.

My App URL: https://athulnair.in/simpleInvoice/public/login

Thank You.

**Comment by tobiasdalhof** [comment]
Hmm, is the app url in your shopify app setup correct? Mine looks like this https://i.imgur.com/MQ5WMAu.png

**Comment by dhruv728462** [comment]
Yes @tobiasdalhof app url setup is correct even installation process is also going well you can install the app and check set up is correct.

**Comment by ohmybrew** [comment]
I dont understand the issue here?

You see the billing screen. [Host: Shopify]
Accepting or decling has a callback URL. [Host: Shopify]
Shopify sends the results to that billing callback URL (full redirect) where the logic is handled [Host: App]
Once completed, billing callback redirects to the home route for the app [Host: App]

If you're taking about the "flash" you see of your entire dashboard without the Shopify wrapping, this is normal. This is due to Shopify loading the page, then seeing its ESDK, then re-running it inside an iframe.

**Comment by dhruv728462** [comment]
Yeah  as you said 
**If you're taking about the "flash" you see of your entire dashboard without the Shopify wrapping, this is normal. This is due to Shopify loading the page, then seeing its ESDK, then re-running it inside an iframe.**

when i have submitted my app so shopify gave me the list of error in which only this error is giving me problem. error is  **There should be no redirects while installing an app let alone any non-secure
sites. Please have this fixed.** 

so whenever i am accepting or decline the billing charge it is going to my [Host App] for logic handled. Is there anyway that i can execute my logic with any redirect to [HOST App].

**Comment by ohmybrew** [comment]
I think something else is going on here, why did they mention non-secure? Is the app entirely on HTTPS?

Theres no way to not do a redirect. Shopify forwards the response (redirect) to the package, the package processes this, then redirects to the homepage.

Installation is the same game... you do a full page redirect to the permissions URL to Shopify. If they accept the app, Shopify redirects you to the callback URL on the package.

Everythings always a redirect...

**Comment by dhruv728462** [comment]
This Non-secure issue i have solved but they are also saying that you should not redirect on any other link after installation process start.

**Comment by fyroc** [comment]
I have been approved many times with the “redirect”. They must be talking
about something else, because all apps does this. Even their own Polaris
React components does this. Are you redirecting off of your apps URL at any
point? Are you sure you have integration enabled?
-- 
Cory C. Fail
Software Engineer
coryfail.com / 912.257.0840

**Comment by ohmybrew** [comment]
I think you'll need to contact them and ask them to explain this because
that sounds absurd.

**Comment by dhruv728462** [comment]
okay thank you very much i should resubmit app and i'll ask them again.
Thank you very much.

**Comment by ohmybrew** [comment]
I'll close for now, but if they respond with something tangible that seems like a bug in the package, please re-open. But as it stands, redirects are core to how Shopify functions for passing information from app to Shopify and Shopify to app during install and billing.
