### ISSUE TITLE
POST requests behaving badly

### ISSUE THREAD

**Issue by paulcanning** [ohmybrew/laravel-shopify#174]
I have an index page which links to a secondary page with a form on it.

I'm linking to this page using a route:

`route('route-name')`

Clicking this link and then filling in the form and submitting, triggers the Shop auth middleware, seemingly because the HMAC, shop domain etc GET params are missing in the URL.

Oddly, just visiting the secondary page does not trigger it, only when submitting the form.

My current fix is to include the GET params form the index page in the route options, but this seems like a kludge.

I am using quite an old version of this library, 3.0.3 - could this be the issue? How much work is involved in upgrading to the latest version?

**Comment by ohmybrew** [comment]
I don't think the version is the issue as much hasnt changed for that stuff between them. I think this is a session issues somehow.

AuthShop wont check the HMAC, it checks that the shop is valid (shop is in session, the shop in session matches what was passed in, we have an access token, shop is not trashed, etc). If any of this info is bad, it sends you to the authentication handler which will handle the HMAC stuff...

I have a POST form right now which seems fine but maybe I'm misunderstanding? So:

1. You're visiting a GET route.
2. You're entering data onto a POST form
3. You POST to a route (clicking submit or whatever)
4. Its sending you to /authenticate ?

If the above is correct then somethings up there... line 35 of Middlewares/AuthShop should return TRUE since a shop is in session.

I'll try to recreate this if thats the case, is there anything special about this form you've made (standard CSRF, etc)?

**Comment by paulcanning** [comment]
Yes, thats the correct flow.

I got the package version wrong btw. I'm actually just using the Basic Shopify API, with my own shop middleware, based on an older version of this package.

```
public function handle(Request $request, Closure $next)
    {
        $shop = Shopify::shop();
        $shop_domain = request('shop');

        if (!$shop ||
            $shop->trashed() ||
            !$shop->shop_token ||
            ($shop_domain && $shop_domain !== $shop->shop_domain) === true
        ) {
            session()->forget('shop_domain');

            session(['return_to' => $request->fullUrl()]);

            return redirect('/authenticate')->with(['shop' => $shop_domain]);
        }

        $response = $next($request);

        if (!$response instanceof Response) {
            // We need a response object to modify headers
            $response = new Response($response);
        }

        if (config('promo-app.esdk_enabled')) {
            // Headers applicable to ESDK only
            $response->headers->set('P3P', 'CP="Not used"');
            $response->headers->remove('X-Frame-Options');
        }

        return $response;
    }
```

**Comment by paulcanning** [comment]
Yes, file base session storage, running in Homestead. But see my edit, about the index page not forwarding to the auth page.

**Comment by ohmybrew** [comment]
Yes the session is set in the auth trait process. So you're saying your code skips the auth?

**Comment by paulcanning** [comment]
It seems to skip creating a session when accessing the app. I think it's because it passes the check as the `shop` $_GET request var is set?

Thats why my kludge works, as I'm adding it to the other URIs. At least, this is my assumption!

**Comment by ohmybrew** [comment]
Passing shop shouldn't work as `$shop` in the middleware should return null if theres no shop already in session... hmm hmmm...

I'll create a standard Laravel form and give it a go and see what I can find. Is your POST simply something like: `<form action="{{ route('some-route') }}" method="post"...>`?
