### ISSUE TITLE
AuthShop middleware authenticate installed shop

### ISSUE THREAD

**Issue by brianakidd** [ohmybrew/laravel-shopify#18]
Thanks for a great package.

If a shop owner has installed the app, do you see any issue with checking the hmac and after confirming the request is from Shopify and that the shop exists in the database, to go ahead and set the shop in the session and continue as an authenticated shop?

Currently, after the shop is installed, it works fine with a current session but after the session expires, within the Shopify admin, the login page is displayed where the user would need to re-enter the shop domain to continue.

I've overwritten the home controller index method with my own and assigned my own web route to the method but it seems to match what ships with this package and includes the auth.shop and billable middleware.  I don't think I'm overlooking anything.

Just making sure I'm not creating a security issue or doing something that may conflict later with this package.  Thanks again.

*** Update ***
I checked back on my development store a few hours later, clicked the app and, this time, my app home page loaded.  I can also see that authentication triggered based on jobs I have running after authentication.

The issue of the login page loading inside of Shopify may be related to something in my code but it's pretty straightforward and I can't see anything in my implementation that would cause it.

**Comment by ohmybrew** [comment]
@brianakidd Hey the auth shop middleware is just simple and is responsible for ensuring we have a shop session, and makes sure theres not a mismatch in shops (example having the app open on two stores in the same browser).

If theres no shop session, they (should) be sent to the auth controller.

Now, the auth controller should have the shop domain passed to it and run through the authentication. The login page should not show... so it sounds like a bug to me in the passing of the shop somehow (I'm hoping Shopify didnt change anything, because, they tend to do this without warning).

Let me try a few things on my end to confirm. Can you please verify this is the problem you're having?

- You load the app, all is fine
- Session later expires in the browser
- Attempt to load app again, it shows login page embedded into the Shopify admin

On the last point, is it you clicking the app name in the Apps page of Shopify which then loads the login, or are you clicking an internal link in your embedded app and it then loads login?

**Comment by brianakidd** [comment]
@ohmybrew Thanks for the response.  Yes, you are describing the flow in your bullets above.  When attempting to load the app again, I am doing so from the Apps page of Shopify by clicking the app name/link.  This is very strange because I've logged in this morning and clicked the app link from the Apps page and it loaded fine.

Based on what I'm seeing, don't spend a lot of time on it.  It may be on Shopify's side - I wish now that I would have inspected the request/response in dev tools but I thought I had an issue and started digging into my code base.

Thanks again.

**Comment by ohmybrew** [comment]
No worries, I'm going to just double check anyways on my end, it won't take too long. Peace of mind :) I'll update this issue on my findings later.

**Comment by ohmybrew** [comment]
@brianakidd Ok so did some digging!

Test 1:
1. Loaded app
2. Cleared cookies for the app domain
3. Clicked app again, it ran me through authentication process fine, app loaded

Test 2:

1. Loaded app
2. Cleared cookies for the app domain
3. Clicked an app internal link, it ran me through authentication process fine, app loaded

Test 3 (knew where this would go, but did it anyways):
1. Loaded app
2. Cleared all cookies (apps and Shopify's)
3. Got kicked out of the Shopify admin
4. Logged in
5. Clicked app, it loaded

I'm not sure what else to physically test to reproduce what happened to you, I'm thinking Shopify borked and maybe didn't pass a shop param in the HTTP request somehow. Theres times things break in the admin in my experience when they push "updates", so maybe it was the case.

If you're cool, I'll close this for now.

**Comment by brianakidd** [comment]
Thanks for the follow up.  I'm closing the issue.
