### ISSUE TITLE
How to impersonate

### ISSUE THREAD

**Issue by hawkfx** [ohmybrew/laravel-shopify#198]
Hello.

There is a way to impersonate to any store? That would be great as an admin

**Comment by ohmybrew** [comment]
There's no built in way to do this. Not sure it's 100% possible since clicking the app in your dev store would cause hmac issues if you spoofed the shop in auth process. You could add a hidden page in your app to switch the shop session (override the Shopify domain session to the new domain and things should work..).

That's all the advice I can offer

**Comment by fyroc** [comment]
Instead of impersonating the accounts, I'd just us a backend to view the data. Impersonations usually means security issues.

https://laravelvoyager.com
