### ISSUE TITLE
[Question] Proxy App 

### ISSUE THREAD

**Issue by azarrar** [ohmybrew/laravel-shopify#199]
Hello, I want to create a custom multiple forms using proxy apps of shopify, but it is written in documentation it should be ".liquid" template engine. Is it necessary to add view file ".liquid" format. Will proxy app suports ".blade" format?

**Comment by ohmybrew** [comment]
You simply need to return content type of application/liquid, your body of the response can be anything.

If you put liquid into your response body, you'll need to escape it from blade since they use a similar syntax. But yes, you can use anything for a response and any engine.

Shopify will take the liquid variables and render them before showing them to the user.

**Comment by azarrar** [comment]
Thanks you sir.

**Comment by BhuvneshSoniApporio** [comment]
When i change the content type into application/liquid . It download the file instead rendering. What possible changes i need to do for that. I am using osiset package to crate shopify app. And using laravel 7.4 version. I am using below code for the proxy url response.

Route::get('/proxy', function () {
  return response('Hello, world!')->withHeaders(['Content-Type' => 'application/liquid']);
})->middleware('auth.proxy');
