### ISSUE TITLE
Losing plan after reinstall

### ISSUE THREAD

**Issue by frexiz** [ohmybrew/laravel-shopify#201]
Hello, what will be the best approach to save user plan when he reinstalls his app? 
Thanks.

**Comment by fyroc** [comment]
The Shop should already be doing a Soft Delete.
Your other models should also be a Soft Delete or just don't cascade when the Shop is uninstalled.

https://github.com/ohmybrew/laravel-shopify/blob/c303f2127e1072f0c4ee1483214b926e9c83139c/src/ShopifyApp/Jobs/AppUninstalledJob.php

**Comment by fyroc** [comment]
I reread this and just incase the above post isn't what you're talking about.

https://github.com/ohmybrew/laravel-shopify/blob/c303f2127e1072f0c4ee1483214b926e9c83139c/src/ShopifyApp/Jobs/AppUninstalledJob.php#L83

The `AppUninstalledJob` removes the plan. This is because the Shop needs to reauth and accept the billing details again after they reinstall the app.

**Comment by ohmybrew** [comment]
Yup, keeping the plan causes issues on reinstall. If you want to keep the plan you can modify the job to store the plan in a new column like "old_plan_id", or you can use a basic query to get a list of the shops last charges (which contains the plan id) and extract the plan from the latest charges.
