### ISSUE TITLE
Override Trial Days for Billing

### ISSUE THREAD

**Issue by eleazargan** [ohmybrew/laravel-shopify#238]
Is there any way that I can override the trial days of the billing plan on-the-go? For example, the shop owner change their billing plan to something else in the middle of the trial, so I want to be able to give him the remaining trial days for the new plan.

**Comment by ohmybrew** [comment]
you'd have to handle this on your own. since they upgraded to a new plan they would be on a new charge, which if you use the package, will default to the trial days you have set for the plan in the database. if you'd like to modify the trial days on the fly before they upgrade to the new plan you'd need to override the billing controller or utilize the billing plan service class to setup your own billing actions

**Comment by eleazargan** [comment]
Yeah I override the billing controller trait and created a new route to point to the new billing controller. Thanks!
