### ISSUE TITLE
Do I have to check charge_id after some time?

### ISSUE THREAD

**Issue by tobiasdalhof** [ohmybrew/laravel-shopify#25]
Hello guys,
first of all, thanks for this package! It saves me plenty of time.

**Following scenario:**

1. Merchant starts 7 day trial -> `charge_id` is being filled
2. Merchant removes the app before the trial ends
3. Merchant installs app again after the trial -> what now? Since billable middleware is just looking for empty `charge_id` fields, the merchant can now use the app for free?

How to handle this situation?

**Comment by brianakidd** [comment]
Hi Tobias, I guess there are a number of ways to handle this.  In my case, I’m subscribing to the uninstall webhook and soft deleting the shop.  This will create a new shop if they choose to reinstall.  This is easiest for me and I don’t need a lot of logic around handling these special cases.

**Comment by brianakidd** [comment]
That seems reasonable to me.  Let’s see if anyone else makes other suggestions.

**Comment by geocoucou** [comment]
I agree, Charge-id alone is not enough. Shopify suggests adding fields to
track the uninstall date (via the webhook) and remaining free days (via
calculation).
Now, if a marketplace reinstalls your app, you can adjust the remaining
free days... so the app can not be free forever with perpetual
reinstallation.

**Comment by tobiasdalhof** [comment]
Awesome, let me know if you need some help

**Comment by ncpope** [comment]
One of the things that soft deleting the shops solves is re-authenticating when the shop uninstalls the app. If you don't re-authenticate after the shop uninstalls, you will receive authentication errors if the shop reinstalls.

Soft deleting is a convenient way to prevent authentication errors.

I would suggest that we should create a charges table and tie it to the shop table using the shop_id column as a key. This way if a shop uninstalls, we can still use soft deletes and we won't have to worry about creating bugs with the authentication process in the case of an uninstall / reinstall.

My proposal would be:
- creating a new model called Charge
- creating a new table called charges
- creating a charges relationship to the shop using the shop_id
- creating a relationship from the shop to the charge using charge_id. These are guaranteed to be unique and provided by Shopify. The column should be indexed for improved queries. This also won't require any additional changes to the shop migration.
- adding soft deletes to the shop model
- adding soft deletes to the shop migration
```
charges table schema
$table->increments('id');
$table->integer('charge_id')->unique(); # filled in when the charge is created, provided by shopify, unique makes it indexed
$table->string('shop_id');
$table->boolean('test');
$table->string('status')->nullable(); #
$table->string('type'); # "recurring", "one_time", "usage", "application_credit": This also allows us to store usage based charges not just subscription or one time charges. We will be able to do things like create a charge history for a shop if they have multiple charges. For instance usage based or an app that has multiple purchases.
$table->decimal('amount', 8, 2); # store the amount of the charge, this helps if you are experimenting with pricing
$table->timestamp('trial_start')->nullable(); # nullable in case of 0 trial days
$table->timestamp('trial_end')->nullable(); # nullable in case of 0 trial days
$table->timestamps(); # provides created_at && updated_at columns
$table->softDeletes(); # allows the shop to delete the shops charges if the app is uninstalled using a webhook. It could also allow the user to cancel the charge from within the app itself if the app allows it.
```

```
update to shops table schema
$table->softDeletes(); # Allows us to remove the shop during an uninstall webhook
`````

Personally I think this is something we should consider instead of tacking on more charge information to the shops table. I don't think more charge information belongs on the shops table. This also allows the developer to create a more robust solution if they want. It is very flexible since it doesn't require a specific billing process.

**Comment by tobiasdalhof** [comment]
+1 on the charges table

**Comment by ncpope** [comment]
@tobiasdalhof great idea. I updated the schema to include it. Also, I revised the names of the columns to match the response attributes.

**Comment by ohmybrew** [comment]
Thanks Nathan, I like it seperate as well. I guess to confirm a shop has
been charged we'll query to see if the shop has a charge which is one time
or recurring (and not soft deleted obviously)?

**Comment by ohmybrew** [comment]
@ncpope In review it looks good. A nice bit of work to be done to implement it so I'm not sure how quick I can pump this out on my schedule (wont be this week anyways).

I'm thinking type in the charge table should be numeric, and the model provides the value via a constant, like `Charge::TYPE_RECURRING`.

In essence the changes required would be (let me know if this sounds correct as well since my brain has been mush from work this week):

1. Modify authentication flow, to check `withTrashed` shops (include soft deleted shops) to see if the shop exists in the database already and they're re-installing. If so, restore the shop, reauthenticate a new token. If not, do normal install process.

2. Modify the billing middleware (if enabled) to check for an active (non deleted) one-time or recurring charge. If no charge found, initiate the normal charge process, store charge data on approve/decline for the shop. If charge is found, continue as normal.

3. Add a model for charges tied to the shop

4. Add helpers on the shop model for grabbing the active charge (if any) and checking if they're still in trial, etc.

I see thats it pretty much? Initially that would be it for release, and build in some charge helpers later.

**Comment by ohmybrew** [comment]
Sorry for the delay in this; been busy at work. Created a new branch for this [here](https://github.com/ohmybrew/laravel-shopify/tree/issue-25-charge-tracking), and have begun some initial setups (table setup, model scopes, etc).

**Comment by ohmybrew** [comment]
Just a note on this... good progress. I've gotten a lot of things situated and tested (unit), going well. I have one remaining piece which is to adjust the billing controller to write a charge (and test of course, with middleware).

**Comment by ohmybrew** [comment]
Regarding the last task I have to do, which is, if a shop uninstalled during trial period, do a new billing charge but for X days instead of the full Y days...

Since the billing plan gets cancelled when the shop uninstalls the app.. I think its best I build in a default uninstall job to the package.

1. Create a publishable job so doing (`php artisan vendor:publish` or `php artisan vendor:publish --tag=jobs`) would put the package's job into `App\Jobs`
2. The job would be bare-bones, simply checking for last recurring/single charge, and marking it cancelled with a date, soft deleting the store.
3. Webhook entry will be in `config/shopify-app.php`, commented out, so user can fill in their server URL

If someone has an existing uninstall job, they can simply not vendor:publish the job, and instead, extend the internal job like such:

```
<?php

namespace App\Jobs;

class AppUninstalledJob extends \OhMyBrew\ShopifyApp\Jobs\AppUninstalledJob implements ShouldQueue
{
    // ....
    public function handle()
    {
        // your current job code here

        $this->cancelCharge();
        $this->softDeleteShop();
    }
}
```

What do you think about the above method... seems the cleanest to me; Default uninstall job, which can be enabled in config, which will soft delete the shop and handle the charges for you.

**Comment by tobiasdalhof** [comment]
Good morning Tyler,

sounds good to me. Will check your feature branch later.

Cheers!

Tyler King <notifications@github.com> schrieb am Mi., 13. Juni 2018, 02:42:

**Comment by ohmybrew** [comment]
Uninstall webhook is completed and tested. Next is to implement the publishable file for vendor publishing, and lastly, determine trial days if applicable on reinstall. Hopefully looking to wrap this up by week's end and do some real world tests to confirm.

**Comment by ohmybrew** [comment]
Code is all completed and unit tested. Will be pushing it up later today. Then I'll be doing some real world tests to ensure all works well!

**Comment by ohmybrew** [comment]
Couple of basic tests worked -- however I got sidetracked with the day job stuff last week as well, so it was halted, planning on taking a evening this week to hopefully finish the real world tests :)

**Comment by ohmybrew** [comment]
I believe I can make a release for this Tuesday. Testing seems to have went fine.

1. Grandfathered shop => Does not get billed, simply installs
2. Shop => Installs, gets asked to bill for X trial days
2a. Shop => Uninstalls, webhook successfully soft deletes charges and shop
2b. Shop => Re-installs a couple days later, trial days decrease by X days, new bill presented
3. Shop => Installs, gets asked to bill for X trial days
3a. Shop => Trial ends, uninstalls
3b. Shop => Reinstalls, no trial presented, they get full bill.

Example of reinstalling a couple days later (original was 7 days, now 5):
![image 2018-07-16 at 12 10 04 am](https://user-images.githubusercontent.com/2420282/42741490-4eb384f6-888d-11e8-9d0f-1dea42a53470.png)

Database keeps a log of all charges to the shop, example is the uninstall, then the new charge activation:
![image 2018-07-16 at 12 11 05 am](https://user-images.githubusercontent.com/2420282/42741491-4ec63fd8-888d-11e8-9637-8cf73f809168.png)

Going to spend tomorrow and write up some new wiki information and upgrade paths. Unfortunately off the top of my head, migrating existing `charge_id`s for 2.x.x of this package to this new version (in the new table) is something I can't provide at this time. You would essentially need to store a map of `shop_id` to `charge_id` somewhere (ie JSON file), run the updates/migrations, run a script to insert the charges into the charge table for the shops. I may be able to provide a artisan command to do this later next week.

Will be releasing asap, good news, long path - sorry for the delays, been super busy!

**Comment by brianakidd** [comment]
@ohmybrew Thanks for all of the work.

**Comment by ohmybrew** [comment]
Released. Hopefully works well. As I said, no pure good upgrade path (database-wise) for the `charge_id` to the charges table currently..

Please read:
1. [Upgrade doc](https://github.com/ohmybrew/laravel-shopify/wiki/Upgrading)
2. [Installation doc for the new app/uninstalled job](https://github.com/ohmybrew/laravel-shopify/wiki/Installation#uninstalled-job-recommended) (optional)
3. [Changelog doc](https://github.com/ohmybrew/laravel-shopify/wiki/Changelog)
4. Also, boring ol' API docs are still available via [phpdoc](https://ohmybrew.com/laravel-shopify)

New version is 3.0.0. I hope to provide a upgrade script to move the `charge_id`s to the charges table within the next couple weeks. But, in the meantime, at least the code is done and out. Thanks everyone for your patience and support for the issue.
