### ISSUE TITLE
Re-Authentication Issue

### ISSUE THREAD

**Issue by prajit21** [ohmybrew/laravel-shopify#272]
Hello,

I have everything set-up and working perfectly.
but Problem with authentication 
we have to use route middleware 'auth.shop' but The only thing I have noticed is that
when I first time authenticate with shopify its working perfectly not an issue but after one day when i open it so its  re-authenticate with it

So give me a better solution please if i missing something

Thanks

**Comment by ohmybrew** [comment]
Can you explain more I don't understand the issue.

**Comment by prajit21** [comment]
we have to use route middleware 'auth.shop' for authentiicate
i mean to say session till 1 day next day to re-authenticate with shopify store
any solution for this ?

**Comment by prajit21** [comment]
i need to re-authorize app everytime after 1 day , it means if i authorize today next it will again ask me to authorize page and add shopify store

any solution for it ?

**Comment by ohmybrew** [comment]
I am not following what the issue is sorry

**Comment by bilfeldt** [comment]
I think we are facing the same issue. This is one way to reproduce the issue

1. Create an [admin link](https://help.shopify.com/en/api/embedded-apps/app-extensions/shopify-admin/app-admin-access) in the Shopify App setup
2. Insert a route in `web.php` for handling the newly created _admin link_ and remember to use the `auth.shop` middleware
3. Implement a simple counter in the controller handling the route and display the count. So basically something like: `Redis::incr('test')`

Now if you have already clicked into one the app pages, then you will have an active session and clicking the _admin link_ will just increment the count by one. But **if** you wait for 24 hours and now click the _admin link_ without having entered any of the pages, then the page will load (hence increment the counter) and the refresh due to some reason I am not sure of and hence increment again. So technically the controller is fired twice.

I can try to make a movie of this if needed @ohmybrew?

**Comment by ohmybrew** [comment]
Fwding to #271
