### ISSUE TITLE
Verify request during development 

### ISSUE THREAD

**Issue by andrewscofield** [ohmybrew/laravel-shopify#345]
I'm trying to create an API (for json data) through Laravel and wanted to setup Postman for testing my API routes and responses. But I'm not sure how to do it correctly because I'm using a dev shopify shop and running laravel on my local machine and the `verifyRequest` is failing every time. Anyway around this for dev mode specifically? This app is already installed and I have a token. 

This works when accessing through shopify admin:
```
$shop = ShopifyApp::shop();
$collections = $shop->api()->rest('GET', '/admin/custom_collections.json')->body->custom_collections;
```

In order to get the same thing to work locally I have done this successfully:
```
$shop = Shop::where('shopify_domain', $shop_domain)->first();
$collections = $shop->api()->rest('GET', '/admin/custom_collections.json')->body->custom_collections;
```

But I'm not sure if I can use the same code all the time or not because I don't know how to get the current session domain. I need to access the shop from both an API controller and other models, whats the best way to do this so I can also test my APIs locally?

**Comment by ohmybrew** [comment]
Your first example will work if you write the shopify_domain session.

**Comment by andrewscofield** [comment]
Can I use this code here somewhere early in bootstrap if my environment is local?

https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Middleware/AuthProxy.php#L39

**Comment by ohmybrew** [comment]
Oh maybe I'm not understanding what you're doing. Are you trying to make a proxy app?On Oct. 21, 2019 19:34, andrewscofield <notifications@github.com> wrote:Can I use this code here somewhere early in bootstrap if my environment is local?
https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Middleware/AuthProxy.php#L39

**Comment by andrewscofield** [comment]
Well I'm writing a shopify admin app using React and Polaris. So far so good, the main trick was the use laravel for an API, instead of normal view rendering. So my hangup was wanting to write tests for my API, and make sure they were all working correctly. But I couldn't find a way to do this outside running a JS fetch within the shopify admin. 

When I run an API call outside of the admin, it errors out saying it fails to verify request. 

Just trying to make life easier during local development.

**Comment by ohmybrew** [comment]
Use the API route file for Laravel, skip the built in middlewares, and handle setting the shopify_domain session on your own and the ShopifyApp::shop() function should work properly On Oct. 21, 2019 20:07, andrewscofield <notifications@github.com> wrote:Well I'm writing a shopify admin app using React and Polaris. So far so good, the main trick was the use laravel for an API, instead of normal view rendering. So my hangup was wanting to write tests for my API, and make sure they were all working correctly. But I couldn't find a way to do this outside running a JS fetch within the shopify admin.
When I run an API call outside of the admin, it errors out saying it fails to verify request.
Just trying to make life easier during local development.

**Comment by andrewscofield** [comment]
@ohmybrew Thanks, that worked! Will removing the middleware give me any issues during normal use?

Also, if you want, I can do a wiki write up on how to use your package to power a Shopify Polaris React app. Its fairly straight forward, but might be of interested to some others.
