### ISSUE TITLE
Auth.shop not redirecting to login if there is no shop

### ISSUE THREAD

**Issue by inazeem** [ohmybrew/laravel-shopify#361]
Some how auth shop have stopped redirecting to login page, if there you land on the homepage.

It  throws this exception 
        // No domain :(

        throw new MissingShopDomainException('Unable to get shop domain.');

![image](https://user-images.githubusercontent.com/3668379/69957257-2ac2a400-14fa-11ea-803a-03a12d838eaa.png)

**Comment by Kyon147** [comment]
Are you on local? 

The AuthShop was changed back in v10 which now throws the exception above.

On production, it will redirect to /login.

**Comment by inazeem** [comment]
Thanks for the quick reply. It is in production but it keeps saying this message.

**Comment by Kyon147** [comment]
In your .env file can you check what your environment is set too?

I suspect you env is set up as "local" when it should say "production"

**Comment by Kyon147** [comment]
Just tried your link and redirects to login for me.
![Screenshot_20191202-124733](https://user-images.githubusercontent.com/32519106/69960688-0074e480-1502-11ea-8dcf-e33e385d1d36.png)

**Comment by Hujjat** [comment]
hey @Kyon147 

I'm getting the same error, I just installed the package on new laravel 6 and I can't view the `/` page. 

I'm getting the same error. 

Please give us some idea. 

Thanks.

**Comment by Kyon147** [comment]
The error happens when the AuthShop is unable to get a valid session and only throws this exception when the app is not in a production environment.  

Are you trying to access the app through Shopify? If you try and access it directly on your local machine like http://127.0.0.1:8000 you will get the above error as you are not passing over all the correct Shopify headers etc.

If you are getting an issue, create a new issue using the template provided and someone can try and reproduce the error.

**Comment by Hujjat** [comment]
Hey @Kyon147 

There is something wrong with route and auth maybe. 

I . have opened an issue here. Please give it a review. #362

Thanks.
