### ISSUE TITLE
App Proxy Redirect loop

### ISSUE THREAD

**Issue by lmartins** [ohmybrew/laravel-shopify#42]
Hi, thanks so much for this awesome library.

I'm exploring in order to explore how viable it would be to add extra functionality for my Shopify projects, and excited for the possibilities this opens.

Going through the install steps, I'm stuck at the App proxy configuration.

I've wen't through the steps for creating the app proxy:
<img width="1150" alt="image 2018-06-10 at 6 32 17 pm" src="https://user-images.githubusercontent.com/151981/41204514-55a1f818-6cdd-11e8-896b-0510288c1562.png">

Checked that the merchant proxy settings use the same defaults, added the route to the Laravel application:

```php
Route::get('/proxy', function () {
  return response('Hello, world!')->withHeaders(['Content-Type' => 'application/liquid']);
})->middleware('auth.proxy');
```

But then each time I try to open the app URL in my browser like `https://merchant.com/apps/product-builder` it keeps redirecting as seen on the ngrok panel:
<img width="1485" alt="image 2018-06-10 at 6 35 46 pm" src="https://user-images.githubusercontent.com/151981/41204516-5c203178-6cdd-11e8-802e-354cad333bc2.png">

I most be missing some crucial step here, could you help?

Thanks!

**Comment by ncpope** [comment]
It's been a while since I tested it but it looks like I had to specify a 200 http response on a proxy I did.

```php
return response($html, 200)->header('Content-Type', 'application/liquid');
```

**Comment by ohmybrew** [comment]
Hmm I'll check this out. But yes, try strictly returning 200. I'll test it out and see if something's changed with Shopify.

**Comment by ohmybrew** [comment]
Are you using Valet? I believe the redirection loop is caused by the Nginx config. I am unable to reproduce. See image attached.

If you're using `valet secure && valet share`, and you're on a free plan, you need to edit your Nginx config in `~/.valet/Nginx` for the site, and comment out the first server block, then run `sudo brew services restart nginx` to make the changes take affect. This will prevent the constant redirect (known issue with Valet + Ngok + Free account).

![068aeef7e0e63bfa2f42bf6eb324220f _image 202018-06-11 20at 2012 46 06 20am](https://user-images.githubusercontent.com/2420282/41211340-497170d0-6d11-11e8-81ae-c650629d3e87.png)

**Comment by lmartins** [comment]
Hi @ohmybrew , thanks so much for the detailed feedback. I am indeed using the setup you describe, so I'll give this a try and confirm the fix.

Thanks so much!

**Comment by ohmybrew** [comment]
Thanks, start valet secure and share. Once running, _then_ edit the nginx entry, then restart nginx and should be good.

**Comment by ohmybrew** [comment]
Hey @lmartins Did the Valet nginx trick help?

**Comment by lmartins** [comment]
Oh, sorry @ohmybrew it did yes. I had to restart valet, not only nginx, not sure why, but other than that it did the trick. Thanks so much for your suggestion and all the work on this library!
