### ISSUE TITLE
404s on the Proxy URL

### ISSUE THREAD

**Issue by lmartins** [ohmybrew/laravel-shopify#45]
Sorry for all the questions.
I'm still a bit puzzled with the site communication with the app via proxy.

I have the app proxy setup as follows:
![image](https://user-images.githubusercontent.com/151981/41501441-63ba3db6-719c-11e8-8fe3-0220082515e9.png)

When i visit the store URL that is linked to this proxy, I see the activity showing up in the ngrok log, however it seems to return an HTML with a redirect in it:

<img width="1423" alt="image 2018-06-16 at 7 37 25 pm" src="https://user-images.githubusercontent.com/151981/41501473-d2cc0694-719c-11e8-85b2-1e99f9c9e475.png">

On the frontend the network activity shows the following:
<img width="1309" alt="image 2018-06-16 at 7 39 31 pm" src="https://user-images.githubusercontent.com/151981/41501485-2001653a-719d-11e8-9e63-64b797b7e801.png">

Any idea what would cause this?

Thanks so much for any help you may provide.

**Comment by lmartins** [comment]
Hi @ncpope , thanks for your input!

I do have the sample home route that came with the default install:

```php
Route::get('/', 'DashboardController@index')->middleware('auth.shop')->name('home');
```

I then have created a minimal test case for the `proxy` route:
```php
Route::get('/proxy', function () {
  return response('Hello, world!', 200)->withHeaders(['Content-Type' => 'application/liquid']);
})->middleware('auth.proxy');
```

On the app proxy settings in Shopify, I have it setup pointing to the root URL:
![image](https://user-images.githubusercontent.com/151981/41529543-76a3f45e-72e5-11e8-9ef2-d63f7b6d5c0f.png)

And was trying to hit the proxy URL by visiting the namespaced url at:

https://3c887b11.ngrok.io/apps/product-builder 

as this was the app proxy URL on the test site:
https://cl.ly/2G2A312Z3F2w

I think I'm missing something, but can't quite understand what.

I was expecting that by hitting the store URL above, I would get the `hello world` message on my screen, instead I get those http error codes for the authentication process.

**Comment by ncpope** [comment]
Hi @lmartins

This is what is happening when you have a proxy and Shopify handles a request to that proxy url:

- User visits `example.myshopify.com/apps/product-builder`
- Shopify makes a request to  your server at: `https://3c887b11.ngrok.io/proxy`
- If your response is Liquid then they will place your response where `{{ content_for_layout }}` is found in the theme
- If your response is valid and not liquid, your response will be the only thing that shows.
- If you response is not valid it will just show 'There was an error in the third party application'

This is how you would fix your issue:

Inside of your shopify partner panel you need to set the url to `https://3c887b11.ngrok.io/proxy` This is because your app doesn't have a route for `/apps/product-builder`. You have the route as `/proxy`

The /apps/product-builder is for the shopify store, the url you enter below that is the url that Shopify will call when a user visits that shopify url.

**Comment by lmartins** [comment]
ahhh that did the trick!!
Thanks so much @ncpope :))))
