### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by akkivaghasiya5** [ohmybrew/laravel-shopify#50]
I have Shopify app developed in my local system (https://myapp.local). Now I want to load it in Shopify (embedded mode). But it is throwing an error '**Refused to display 'https://myapp.local/embedded/forms?hmac=xxxxxxxxxxxxxxxx&locale=en&protocol=https%3A%2F%2F&shop=myshop.myshopify.com&timestamp=1529929088' in a frame because it set 'X-Frame-Options' to 'deny'.**' I have set `SHOPIFY_ESDK_ENABLED = 1` as well as required settings in partners.shopify also. When I have installed this package 3 months ago, it was getting loaded. But now it's not getting loaded. After debugging, I come to know that `$response->headers->remove('X-Frame-Options');` of `OhMyBrew\ShopifyApp\Middleware\AuthShop` should remove the header while **SHOPIFY_ESDK_ENABLED** is set to 1. But it's not removing. I don't know either it's a bug or something related to laravel or apache2. So can anyone look into this?

Here is my virtual host file

```
<IfModule mod_ssl.c>
    <VirtualHost _default_:443>
        ServerAdmin webmaster
        ServerName myapp.local
        ServerAlias www.myapp.local
        DocumentRoot /var/www/myapp/public
        <Directory /var/www/myapp/public>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        SSLEngine on
        SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
        SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
            SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
            SSLOptions +StdEnvVars
        </Directory>
    </VirtualHost>
</IfModule>
```

**Comment by ohmybrew** [comment]
Hey, I can confirm its removed on my test shop so I think something else is interfering here. Can you try adding the x frames, and other headers to your virtual hosts and see what happens?

**Comment by akkivaghasiya5** [comment]
@ohmybrew You are right. But I don't know why it happens? BDW, I'm on ubuntu 16.04, apache2, laravel 5.6

**Comment by akkivaghasiya5** [comment]
On adding **Header always unset X-Frame-Options** in ./public/.htaccess, it is working. But this is not a proper solution as it removes X-Frame-Options header from all the requests.

**Comment by akkivaghasiya5** [comment]
Here is what I have done until now.

In **/etc/apache2/conf-available/ssl-params.conf**, I have commented this line and restarted apache
`#Header always set X-Frame-Options DENY`

In **./public/.htaccess**, added this line
`Header always unset X-Frame-Options`

And it works. But this is not a proper solution as it removes X-Frame-Options header from all the requests. So I have changed the line in .htaccess from `Header always unset X-Frame-Options` to `Header set X-Frame-Options DENY` (note that its Header set, not Header always set). And AuthShop middleware is removing the header whenever it required. So I thought it will remove the header. But it is not working.

**Comment by ohmybrew** [comment]
I am unable to produce with Nginx setup. I wonder if Laravel's FrameGuard is getting in the way?

**Comment by ohmybrew** [comment]
So who's setting deny? Hmm. I think apache is interfering here then? If so
you may be stuck with using headers on your config.

**Comment by akkivaghasiya5** [comment]
@ohmybrew You are correct. And I have already done it before a day. Please see the fourth comment on this issue.

Here is what I have done until now.

In **/etc/apache2/conf-available/ssl-params.conf**, I have commented this line and restarted apache
`#Header always set X-Frame-Options DENY`

In **./public/.htaccess**, added this line
`Header always unset X-Frame-Options`

And it works. But this is not a proper solution as it removes X-Frame-Options header from all the requests. So I have changed the line in .htaccess from `Header always unset X-Frame-Options` to `Header set X-Frame-Options DENY` (note that its Header set, not Header always set). And AuthShop middleware is removing the header whenever it required. So I thought it will remove the header. But it is not working.

**Comment by ohmybrew** [comment]
Alright well in this case I think it's out of my hands to correct. The code
can try but it seems to be overruled.

I had similar issues sometimes when using shopify_app gem even though it
does the same thing and removes the headers I still had to tell the config
to remove it.

I'll make a page for this in the wiki and close for now.

On Jun 27, 2018 9:16 AM, "Akshay Vaghasiya" <notifications@github.com>
wrote:

@ohmybrew <https://github.com/ohmybrew> You are correct. And I have already
done it before a day. Please see the fourth comment on this issue.

Here is what I have done until now.

In */etc/apache2/conf-available/ssl-params.conf*, I have commented this
line and restarted apache
#Header always set X-Frame-Options DENY

In *./public/.htaccess*, added this line
Header always unset X-Frame-Options

And it works. But this is not a proper solution as it removes
X-Frame-Options header from all the requests. So I have changed the line in
.htaccess from Header always unset X-Frame-Options to Header set
X-Frame-Options DENY (note that its Header set, not Header always set). And
AuthShop middleware is removing the header whenever it required. So I
thought it will remove the header. But it is not working.

—

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ohmybrew/laravel-shopify/issues/50#issuecomment-400643434>,
or mute the thread

**Comment by ncpope** [comment]
Similarly, for nginx you will need to comment out this line if it is found in your config:

```
# add_header X-Frame-Options "SAMEORIGIN";
```

**Comment by ohmybrew** [comment]
@amosmos ah thought it was open to all? I'll adjust this after my flights today. I'll add this in too, thanks for the note.

**Comment by ohmybrew** [comment]
Wiki is now open.
