### ISSUE TITLE
Webhooks don't work

### ISSUE THREAD

**Issue by demoskp** [ohmybrew/laravel-shopify#64]
I have updated the package to 2.2.0 and my webhooks stopped working, my guess is that the domain token has changed. 

Am I not able to call the shop domain from my webhook job using $shopDomain and the response from shopify with $data?

**Comment by ohmybrew** [comment]
I just tested a webhook and all went well on my end, do you have any error messages?

**Comment by demoskp** [comment]
I am getting undefined variable shopDomain

**Comment by ohmybrew** [comment]
Shop domain comes from x-shopify-shop-domain header and body comes from the request. You're saying you're not getting either?

What type of webhook is this?
Can you share the constructor?
Is it going through the webhook controller or did you do something custom?

Odd because the auth.webhook middleware would fail if the shop was missing.

**Comment by ohmybrew** [comment]
Shop domain comes from x-shopify-shop-domain header and body comes from the request. You're saying you're not getting either?

What type of webhook is this?
Can you share the constructor?
Is it going through the webhook controller or did you do something custom?

Odd because the auth.webhook middleware would fail if the shop was missing.

**Comment by demoskp** [comment]
I tried it on another page and I get that error. Is that only valid for the webhook? 

The webhook gets the request from shopify and gives it to the worker which is then processed, I do not get any errors in my worker database tables but when I try any webhook it doesn't actually do what it should. Would the errors appear in the laravel log or the php log?

**Comment by demoskp** [comment]
public function __construct($shopDomain, $data)
    {
        $this->shopDomain = $shopDomain;
        $this->data = $data;
    }

**Comment by ohmybrew** [comment]
When you say you try the job, what do you mean by this?

If theres any errors it may be in the php/laravel log yes. If the job gets the queue, then it has passed the validation on the middleware, which means it should have all the data it needs to run.

**Comment by demoskp** [comment]
I used different webhook actions such as delete a product from my shopify store, as well as delete the app but it doesn't process anything from the database.

**Comment by brianakidd** [comment]
@demoskp Can you share the route, the controller action that the route points to, your webhook job and your shopify-app config file showing the webhook?

This is going to be difficult to troubleshoot without having the entire flow.  Thanks.

**Comment by demoskp** [comment]
It was my fault, I had changed a domain for the app but forgot to update the webhook links in the app configuration.
