### ISSUE TITLE
HomeController not found

### ISSUE THREAD

**Issue by paulcanning** [ohmybrew/laravel-shopify#72]
After following the instructions [here](https://github.com/ohmybrew/laravel-shopify/wiki/Overriding-and-Extending) to change the web routing, the application cannot find HomeController.php - it seems to be in the vendor package, but it is not copied across to my app/controller folder?

**Comment by ohmybrew** [comment]
Maybe it needs to be worded better.. its just an example essentially, wiki says:

`will now point to your HomeController where you can return your own code/view or optionally extend \OhMyBrew\ShopifyApp\Controllers\HomeController`

So it assumes you have a "HomeController" file or similar.

You can extend the [built in controller](https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Controllers/HomeController.php). But in reality, it just uses a trait; so you can simply include the trait into the controller.

However, furthur-more, the trait simply includes a dummy index method which includes the "Welcome" screen and sets up the ESDK items.

Overall, I think its not important, so long as you extend the main [layout file](https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php) in your views, since it setups the ESDK items for you.

**Comment by paulcanning** [comment]
Yes, I think the big issue here is the documentation isn't very clear.

If you simply follow the instructions in the wiki, you will not get a working app. The video helps a bit more, but again, it's missing important steps.

**Comment by ohmybrew** [comment]
The install works, as far as doing your own controllers and such, I don't
have this as the install process. I'll see about working on the docs for
this once I push out some fixes! Thanks.

On Aug. 15, 2018 1:08 p.m., "Paul Canning" <notifications@github.com> wrote:

Yes, I think the big issue here is the documentation isn't very clear.

If you simply follow the instructions in the wiki, you will not get a
working app. The video helps a bit more, but again, it's missing important
steps.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ohmybrew/laravel-shopify/issues/72#issuecomment-413237749>,
or mute the thread

**Comment by ohmybrew** [comment]
Edited the doc to be a bit more clear... (hopefully). If theres any else you feel missing, feel free to let me know, i'll gladly add.

**Comment by rameshelamathi** [comment]
One more instruction would clear the doubts.

When installing Laravel, it adds a default route to the web.php for the home (/)
After following the installation instructions, you should edit /routes/web.php
Comment out or remove 
`Route::get('/', function () {
    return view('welcome');
});`
