### ISSUE TITLE
embedded app need to login

### ISSUE THREAD

**Issue by hakimihamdan88** [ohmybrew/laravel-shopify#99]
how do I prevent this from happening?
its seems session is expired.

![screen shot 2018-09-07 at 5 47 53 pm](https://user-images.githubusercontent.com/1689992/45212055-7e7a1980-b2c6-11e8-8070-013b10653645.png)

**Comment by ohmybrew** [comment]
What were the steps for this

**Comment by fyroc** [comment]
You get this whenever the Shopify session/login expires.

**Comment by fyroc** [comment]
I guess the best way to handle this, is if the app expires, don't take them to the /login page. Instead, can we have the option of taking them to an error page saying the session expired?

**Comment by ohmybrew** [comment]
Possible yes. But there's something going on... If it's inside the iframe,
then a shop was sent, of the session was bad, it should redirect to auth,
I'm able to reproduce this by deleting cookies, etc, so I'm not sure the
flow here, need more info I think.

**Comment by ohmybrew** [comment]
@fyroc By session expire you mean *Shopify*'s session expires? As in you're logged out?

If so, yeah... this would be a different beast, I could see about a work around for that.

**Comment by ohmybrew** [comment]
As per above, not sure what else I can do. If the session is killed, theres no shop domain in storage so it kicks to install page. Several apps I've tried on the store do a mix of showing the install page, timing out, or causing a 500 error. I've opted to leave as is, as I think thats all I can do... in commit 6c569bf I've updated the messaging for the "install" page to be more "login" friendly in text so customer will not think they're installing it once again. I'll apply this in a patch release soon.

Only other work around I tested, is to apply "?shop=[myshopifydomain]" to every internal link of the app, because even if the session gets killed off, it will rerun the auth with the shop domain, however this may not be a good work around for everyone.
